steps:
  # Step 1: Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  # Step 2: Install dependencies
  - script: |
      npm install
    displayName: 'Install dependencies'

  # Step 3: Run tests
  - script: |
      npm test
    displayName: 'Run tests'

  # Step 4: Create deployment package
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/application.zip'
      replaceExistingArchive: true
      verbose: true
      excludeFiles: '**/node_modules/**'

  # Step 5: Deploy the application
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'SOCARTRADING Test'
      appName: 'aktest777'
      package: '$(Build.ArtifactStagingDirectory)/application.zip'
    displayName: 'Deploy the application'
